# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ba8df0c377d05e6b92e288fb60397e13075d4aaf4edb291d3f55fa6706ca289c4731aa5bbc9f554782e55fe10bac09f2c4e6e16df3dee9f43d369f9a676e5e4

test:
  secret_key_base: d3e79eb9383258d46921b5ce05e12263fa6972181d7f97f0247690066400f15f5b30ff343d7e25494daba1b8da74d3d9d80cabee17ed6302a33156eae2838617

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
